services:
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      -  rede-sejusc
    depends_on:
      - mysql
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestao-rh
      MYSQL_USER: sejusc
      MYSQL_PASSWORD: senhatopzona
    networks:
      - rede-sejusc
      - volumes:
      - mysql-data:/var/lib/mysql


networks:
  rede-sejusc:
    driver: bridge