services:
  adminer:
    container_name: adminer-rede-sejusc
    image: adminer
    ports:
      - 8080:8080
    networks:
      -  rede-sejusc
    depends_on:
      - mysql
  mysql:
    container_name: mysql-rede-sejusc
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestao-rh
      MYSQL_USER: sejusc
      MYSQL_PASSWORD: senhatopzona
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      -  rede-sejusc

volumes:
  mysql_data:

networks:
  rede-sejusc:
    driver: bridge